# Site settings
title: Amethyst Nail Studio
email: jason@jasonhardin.com
author: Jason Hardin
description:
url: "http://www.amethystnailstudio.com" # the base hostname & protocol for your site
facebook_username:
instagram_id:

sass:
  style: compressed

theme: jekyll-theme-cayman
