# Site settings
title: Amethyst Nail Studio
email: norcal212@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amethystnailstudio.com" # the base hostname & protocol for your site

facebook_username: Amethyst-Nail-Studio-102458987980224
instagram_username: amethystnailstudio
book_url: https://www.fresha.com/providers/amethyst-nail-studio-i2cpdkdf?pId=342804

google_maps_javascript_api_key: "AIzaSyA0low6IO6HFXBXxRGyWVFYGpiGTmh-eTY"

# Build settings
markdown: kramdown
